name: index_page
version: 0.1.0
description: >
  Transformer which outputs a simple index.html file in all folders under web
  when one is not already present.
author: Jake MacDonald <jakemac53@gmail.com>
homepage: https://github.com/dart-lang/index_page
dependencies:
  barback: '>=0.14.2 <0.16.0'
  path: ^1.0.0
transformers:
- index_page:
    $include: example/**.html
environment:
  sdk: '>=1.9.0 <2.0.0'
